language: python
cache:
- pip
sudo: false
os:
- linux
stages:
- spell
- docs
- test
- deploy
script:
notifications:
  email:
  - pycontribs@googlegroups.com
  - sorin.sbarnea@gmail.com  
jobs:
  include:

  - stage: docs
    script: pip install -q tox-travis && python -m tox
    python: 2.7
    env: TOXENV=docs
  - stage: test
    script: pip install -q tox-travis && python -m tox
    python: 2.7
    env: TOXENV=py27
    after_success:
    - bash <(curl -s https://codecov.io/bash) -e TOX_ENV
    - requires.io update-site -t ac3bbcca32ae03237a6aae2b02eb9411045489bb -r
  - stage: test
    script: pip install -q tox-travis && python -m tox
    python: 3.4
    env: TOXENV=py34
    after_success:
    - bash <(curl -s https://codecov.io/bash) -e TOX_ENV
  - stage: test
    script: pip install -q tox-travis && python -m tox
    python: 3.5
    env: TOXENV=py35
    after_success:
    - bash <(curl -s https://codecov.io/bash) -e TOX_ENV
  - stage: test
    script: pip install -q tox-travis && python -m tox
    python: 3.6
    env: TOXENV=py36 PYTHON='3.6' PYENV_VERSION='system'
    after_success:
    - bash <(curl -s https://codecov.io/bash) -e TOX_ENV
install:
  - tox
script: tox

